### ISSUE TITLE
File uploads to web console broken

### ISSUE THREAD

**Issue by r0pchain** [code-genome/codegenome#1]
I've attempted both the "Quick Start" and "Local Docker Build" and gotten the same results in screenshot

To repro:

cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

make start

Open Firefox to localhost:5000

![Screenshot 2024-10-08 141328](https://github.com/user-attachments/assets/0a6afa11-5844-4e40-bcfb-6acda08e0ff3)

**Comment by dhilung** [comment]
Hi @r0pchain, thank you for reporting the issue. 

Looks like there is a docker mount permission bug that is [fixed here](https://github.com/code-genome/codegenome/commit/5aba19bcfe48fba117324bf3c955395b3c60240c).

You may run `sudo chown -R 1001:1001 ~/.cg` or pull the latest changes and try `make start` again.

**Comment by r0pchain** [comment]
Confirmed fixed
![image](https://github.com/user-attachments/assets/40217398-ac85-4dca-83d4-dc2c990ee8e5)
